version: '3'

services:
  db:
    image: mysql:8
    ports:
        - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Passw0rd
      - MYSQL_DATABASE=deno-dev
      - TZ=Asia/Tokyo
    volumes:
      - db-volume:/var/lib/mysql
      - ./docker/db/config/mysql:/etc/mysql/conf.d
      - ./logs:/var/log/mysql

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-volume:
